### ISSUE TITLE
Add fuzzy category imports

### ISSUE THREAD

**Issue by OmgImAlexis** [bitcannon-org/bitcannon-core#1]
Instead of relying on the import to tell us the category and then using a string we should have a model for categories and then use regex to search for a category similar to the one in the import for example we'd search for `TV`, `tV ShOWs` and find `TV Shows`. We'd make sure to use `.toLowerCase()` and a `LIKE` search on mongoose.

On the first run we can try the string and then if it doesn't match at all we could add an error to the log and alert the user after the import is finished, that way people will report the issue to us and we can add an exception or tweak the import regex to match it better. Obviously as there aren't all that many sites to get dumps from this should get quite accurate quite quickly.

@bitcannon-org/owners

**Comment by stephen304** [comment]
Yeah I could have made the old system a bit better by lowercasing the compare and using partial matches.

Part of the problem is that torrent sites use lots of different categories and break down things in different ways. Like KAT has an anime category but other sites may lump it with tv shows. We could try to make mappings like anime -> tv shows but that would end up varying based on personal preference. 

I think making a built in list of mappings would cover a lot of the cases since, as you said, there are only so many categories on all the torrent sites and they don't change that often, so simple mappings (like anime -> tv shows) would be my preferred solution. It should be configurable and people would be able to send us their mappings so we can add more to be included by default (some disabled if they are questionable or not popular).

I think the structure for the settings would be something like

```
[
  {
    name: "Movies",
    aliases: [
      {
        name: "videos",
        enabled: true
      },
      {
        name: "anime",
        enabled: true
      }
    ]
  },
  {
    name: "TV Shows",
    aliases: [
      {
        name: "tv",
        enabled: true
      },
      {
        name: "serieses",
        enabled: false
      }
    ]
  }
]
```

This would map all aliases back to the main category.

**Comment by OmgImAlexis** [comment]
Exactly, we'd also need a "url" field in there for `/browse/:category` listing but that would well. We could also enable the option to add, remove and disable the different aliases which would really come in handy if we added anonymous feedback in the sense. If a user enables it once a month or something we send a post request to the bitcannon server with the aliases they have so we can fine tune them. Obviously all of that would be opt in/out.

**Comment by stephen304** [comment]
Yeah that's what I was getting with the enabled flag. I was thinking of opt
in automatic feedback too, but that's for later.

**Comment by OmgImAlexis** [comment]
We're going to have to build a "converter" for people wanting to switch to the node version so we can normalise categories.
For now what I've done on mine is add a new category called `TV` like this.

````
{ 
    "title" : "TV", 
    "url" : "tv", 
    "aliases" : [
        "tv show", 
        "show", 
        "episode"
    ]
}
````

Then once I got the _id I ran this command in Mongo.

````
use bitcannon;
db.torrents.update({category: 'TV'}, { '$set': { category: ObjectId("56455aff036463f20aa07541") }}, {multi: true});
db.torrents.update({category: 'Video TV'}, { '$set': { category: ObjectId("56455aff036463f20aa07541") }}, {multi: true});
````

**Comment by stephen304** [comment]
Isn't URL just a slug of the category? Just to keep the structure concise.

**Comment by OmgImAlexis** [comment]
Yes, I'll change that to slug now and add in a bit of code to convert the "title" to a clean slug. e.g. remove symbols and make it lowercase.

Should we be using "title" or "name" for categories?

**Comment by stephen304** [comment]
I think title works fine. The slug can just be found from the title on the
fly as needed so you don't have to have 2 fields.

**Comment by OmgImAlexis** [comment]
The space saved from not having a slug field isn't worth the performance hit. Already did tests on my own blog when I added in slugs.

**Comment by stephen304** [comment]
I don't mean the space but the complexity. It would be annoying to have to
deal with the extra field when writing configs when it's just a slugified
name. It provides no extra information.

**Comment by stephen304** [comment]
Also the performance hit of generating it on the fly is negligible.

**Comment by OmgImAlexis** [comment]
What do you mean? This does nothing but helps with indexing the field. Anything they change in the config, etc. would updated the title and then the slug with auto-gen again.

**Comment by stephen304** [comment]
I just don't see a reason to save the slug. The configuration would look
simpler without it, and I want to avoid unnecessary complexity. The slug
should always be the slugified title so I'd prefer to generate it when
needed.

**Comment by OmgImAlexis** [comment]
What configuration? There's literally nothing that this will change for the user. All this is doing is "caching" the slug instead of generating it on the fly. When you've got an outside process searching for things using the API we can also add can do a text search of the indexes of the title of the torrent and category along with a bunch of other things this helps with that.

**Comment by stephen304** [comment]
The configuration that these settings save to. Also any code that changes
it wouldn't have to worry about forgetting to change both so you wouldn't
have to worry about the slug and title being inconsistent.

**Comment by stephen304** [comment]
I don't see much reason to cache what can be generated in a couple string
operations. Especially when it makes config easier to reason about.

**Comment by OmgImAlexis** [comment]
That's what I was saying.... Nothing changes. Guessing you haven't done much with mongoose. 
Either we use a virtual or save it, this will auto gen and save the new slug everytime it changes the title.

Simple as that. Also the config has NOTHING to do with the slug.

````
var mongoose = require('mongoose');

var categorySchema = mongoose.Schema({
    title: String,
    slug: String,
    aliases: [
        String
    ]
});

function slugify(text) {
      return text.toString().toLowerCase()
        .replace(/\s+/g, '-')        // Replace spaces with -
        .replace(/[^\w\-]+/g, '')   // Remove all non-word chars
        .replace(/\-\-+/g, '-')      // Replace multiple - with single -
        .replace(/^-+/, '')          // Trim - from start of text
        .replace(/-+$/, '');         // Trim - from end of text
}

categorySchema.pre('save', function (next) {
    this.slug = slugify(this.title);
    next();
});

module.exports = mongoose.model('Category', categorySchema);
````

**Comment by stephen304** [comment]
Are we storing the config in the database?

**Comment by OmgImAlexis** [comment]
What config? This?

````
{
    "web": {
        "port": 3000,
        "title": "BitCannon",
        "torrentsPerPage": 100
    },
    "database": {
        "host": "localhost",
        "port": 27017,
        "collection": "bitcannon"
    },
    "session": {
        "secret": "asdaskdmlaskmd3j4n2k3j4nkj23n"
    },
    "trackers": "",
    "downloads": {
        "hourly": {
            "kat": ""
        },
        "daily": {
            "tpb": ""
        }
    }
}
````

**Comment by stephen304** [comment]
The category configuration we've been talking about

**Comment by OmgImAlexis** [comment]
That'll be in the setting's menu and it'll basically be an interface with the category collection. It'll show the title, aliases, etc. and they'll be able to change them and remove them. Obviously if they remove a category and there's torrents with that set they'll be given the option to remove them or migrate them to a new one or remove the category meaning they'll be in a "default" one.

Maybe we're getting what I'm talking about mixed up.

**Comment by stephen304** [comment]
I get it'll be accessible in the GUI but where were you intending on
storing the actual settings? I've been assuming it would be the same as the
original bitcannon with a json file but then you mentioned that I probably
haven't looked at mongoose and I'm not sure why that's relevant unless
you're been thinking of storing the category configuration in the database?

**Comment by OmgImAlexis** [comment]
In the database there's a model called category, to keep things working over 1M torrents we NEED indexes especially if people want to use this as an API endpoint for things like SickRage, CouchPotato, etc.

If you have a look at the develop branch of bitcannon-web you'll notice there's a model for categories.

````
var mongoose = require('mongoose');

var categorySchema = mongoose.Schema({
    title: String,
    slug: String,
    aliases: [
        String
    ]
});

function slugify(text) {
      return text.toString().toLowerCase()
        .replace(/\s+/g, '-')        // Replace spaces with -
        .replace(/[^\w\-]+/g, '')   // Remove all non-word chars
        .replace(/\-\-+/g, '-')      // Replace multiple - with single -
        .replace(/^-+/, '')          // Trim - from start of text
        .replace(/-+$/, '');         // Trim - from end of text
}

categorySchema.pre('save', function (next) {
    this.slug = slugify(this.title);
    next();
});

module.exports = mongoose.model('Category', categorySchema);
````

What will happen is when a torrent is added it'll search the title and aliases for a match and then add the category to the torrent on import like this.

````
{ 
    "_id" : ObjectId("56454a0d8cd6c6377a59b917"), 
    "title" : "The Biology Book - From the Origin of Life to Epigenics, 250 Milestones in the History of Biology (2015).epub Gooner", 
    "category" : ObjectId("564560c3036463f20aa07549"), 
    "size" : NumberInt(0), 
    "details" : [
        "http://www.demonoid.ooo/files/details/3294998/"
    ], 
    "swarm" : {
        "seeders" : NumberInt(77), 
        "leechers" : NumberInt(18)
    }, 
    "lastmod" : ISODate("2015-11-13T00:58:55.374+0000"), 
    "imported" : ISODate("2015-11-13T00:58:51.460+0000"), 
    "infoHash" : "037AEA6B6D89CA57877AB6EC9011F058416A5538"
}
````

This is how mongodb is meant to be used. You'll also notice the ID isn't the infoHash anymore as you're meant to use an ObjectId for the _id field.

**Comment by OmgImAlexis** [comment]
To get the category title, etc. on a torrent we just populate the field like so.

````
Torrent.find({}).limit(limit).populate('category').exec(function(err, torrents) {
            if(err) { console.log(err); }
            res.render('search', {
                torrents: torrents
            });
        });
````

**Comment by stephen304** [comment]
Yeah I mean I had indexes on old bitcannon too, that's what made queries
execute in reasonable time. It was just convenient to store categories in a
json file. If we're putting it in the database then I don't care as much
what other fields you stick on them especially if they're virtual since
nobody can or should hand edit it.

As you can tell I haven't even glanced at what you have so far because I've
been doing school.

**Comment by OmgImAlexis** [comment]
All's good, hopefully once you get a chance to have a look around the new code it'll make more sense on what I'm doing.

By the way most of the web interface is done so I might work on adding some other stuff in like admin login, etc. so if someone wants to move files, etc. they can. What do you think of adding in comments? If we did something like that and allowed people to upload their own torrents and stuff this could also be used as a framework for a torrent site. Not exactly sure where you're going with this project.

**Comment by OmgImAlexis** [comment]
@stephen304 just wondering if we're still going with this, haven't heard from you in about a week.

**Comment by stephen304** [comment]
Yeah I've just been busy with finals week approaching. Like I said, I won't
be active really until the semester is over.

**Comment by OmgImAlexis** [comment]
Alright. What's the timeline for that? School, etc. has already finished a few weeks ago in my country.

**Comment by stephen304** [comment]
Ah I see. Here it lines up with new year so I'm done mid December (if I was
going to school next semester it would start back in January after
Christmas break.)

So I have a couple weeks left basically.

**Comment by OmgImAlexis** [comment]
Okay. Sounds good. I'll finish the rest of the web stuff and then just wait for you to start adding in the Go --> Node code.

**Comment by OmgImAlexis** [comment]
@stephen304 I've been speaking to the SickRage team and there's some other things they've mentioned that'd be nice to have on bitcannon but I'm not sure if it's going in the way you'd like bitcannon to go so should we rebrand this as a new project or just add the new features? The main one is adding Torznab support. https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

**Comment by stephen304** [comment]
That would just be a few more endpoints right? If I understand correctly
it's just a new way of querying the database?

**Comment by OmgImAlexis** [comment]
A bit of both, we'd have another end point for it like /torznab instead of /api

**Comment by stephen304** [comment]
I'm a little tired but it looks like torznab is an api standard of sorts?
I'm all for adding it once the core features are functional.

**Comment by OmgImAlexis** [comment]
Yep that's kind of what it is. I'm still trying to wrap my head around it.

Okay, well I've only got a few things to add and then we're good.
